Section "Monitor"
### Monitor Identity - Typically HDMI-0 or DisplayPort-0
    Identifier    "Virtual-1" 
    Option        "PreferredMode" "2560x1440"
    Option        "TargetRefresh" "120"

EndSection 
